[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://invoice-generator-5cs6.onrender.com"

# Redirect all routes to index.html for single-page applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
