services:
  - type: web
    name: invoice-generator
    env: node
    buildCommand: npm run deploy
    startCommand: node backend/server.js
    healthCheckPath: /api/health
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        fromDatabase:
          name: invoice-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d

databases:
  - name: invoice-mongodb
    databaseName: invoice_generator
    user: admin
    plan: starter
